name: Build and push container image to quay.io
on:
  push:
    branches:
    - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      id: qemu-setup
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker buildx
      id: buildx-setup
      uses: docker/setup-buildx-action@v1

    - name: Login to quay.io container registry
      id: docker-login
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image
      id: docker-build-push
      uses: docker/build-push-action@v2
      with:
        file: Containerfile
        push: true
        tags: quay.io/currybullen/berit:latest quay.io/currybullen/berit:${{ github.sha }}
