name: Build and push image
on: [ push ]

jobs:
  build:
    name: Build and push image
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Login to quay.io container registry
      id: docker-login
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username:  currybullen+github
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image
      id: docker-build
      run: |
        docker build . -f Containerfile -t quay.io/currybullen/berit:latest -t quay.io/currybullen/berit:${{ github.sha }}
        docker push quay.io/currybullen/berit
        docker image rm quay.io/currybullen/berit:${{ github.sha }}
